#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PingAppAndroid.Resource", IsApplication=true)]

namespace PingAppAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int dropdown_arrays = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int edit_text_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int FriendListBtn = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int LogOutBtn = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int NotificationsBtn = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int PingIcon = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int PingTime = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int PingUserName = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int ProfileBtn = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int RecentPings = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int Settings = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int TxtLastName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int TxtUserName = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int button1 = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int editText1 = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int editText2 = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int friendList = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int searchbarFriend = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int spinner1 = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int toolbar1 = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FriendRowView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Friends = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Notification = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PingRowView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Profile = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int LogOutBtn = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Settings = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int UserName = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int searchbarHint = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
